### ISSUE TITLE
Fix State Panel

### ISSUE THREAD

**Issue by Pedro12909** [aerospaceresearch/Universal-Space-Operations-Center#12]
It looks like while porting the UI from Swing to JavaFX, the state panel's formatting got messed up, at least on a Linux Environment, as seen below:
![Ubuntu 17.10](https://image.ibb.co/b5w0V7/Screenshot_from_2018_03_06_14_48_42.png)

What should be displayed in the State Panel? I would like to start fixing this.

**Comment by vstarlinger** [comment]
Hi Pedro, I have an exam tomorrow and will write you a detailed answer afterwards. Thanks for all the time you put into this!

**Comment by Pedro12909** [comment]
Good luck!

**Comment by vstarlinger** [comment]
Hi, Pedro. Yes the State Panel got messed up a bit 😅
The original State Panel looked like this:

[somehow image upload didn't work](https://imgur.com/a/rTjhs)

With the states in the top part either being green or red depending on the current state of that sensor.

**Comment by Pedro12909** [comment]
From my understanding, there's two types of segments that should be inside the state panel:
- The state's segment, that contains a grid of labels (these labels are in the properties file). Are these labels supposed to be updated?
- An arbitrary number of MCU segments . How many of these segments should be instantiated? Should it be asked in the properties file?
