### ISSUE TITLE
GNSSPanel doesn’t work with JavaFX

### ISSUE THREAD

**Issue by vstarlinger** [aerospaceresearch/Universal-Space-Operations-Center#5]
Somehow a Thread is not terminated on window close so program keeps running in the background.

**Comment by Pedro12909** [comment]
I've created a PR that fixes this being overriding the Application stop() method and force closing all threads. However, this doesn't look like a optimal fix. After some researching the problem, I think the problem resides in the 3 Worlwind Panels not closing on shutdown. I think I can fix this, but I'm not sure how to access the panels's instances to shut them down. Any help would be appreciated

**Comment by vstarlinger** [comment]
Do you want to access the panels from the main method in `GroundSegment.java`?

**Comment by vstarlinger** [comment]
You could have a Singletonpattern for the GNSSPanel and then call `GNSSPanel.getInstance().shutdown()`. I don't think that there will ever be more than one GNSSPanel present so this should be fine.

**Comment by Pedro12909** [comment]
Apparently `shutdown()` doesn't seem to work. I closed all worldwind panels manually but there are still active threads running in the background and I can't figure out what is causing that and how to shut them down.
