### ISSUE TITLE
[Wiki] Overview Tab has duplicate text

### ISSUE THREAD

**Issue by Pedro12909** [aerospaceresearch/Universal-Space-Operations-Center#8]
The [Overview](https://github.com/aerospaceresearch/Universal-Space-Operations-Center/wiki/Overview) section of the wiki has duplicate text:

> The main controller coordinates the communication between the GUI and the other USOC components. It is implemented using a Singleton Pattern which means that it can easily be accessed from anywhere in the code. Before visualizing the data in the GUI, it can be modified in the DataModification class.The MessageController acts as an interface between the internal data storage and the MainController and is also responsible for parsing incoming data. For doing that it requires the protocol structure which is provided through the XMLReader. The SerialCommunication class is sending and receiving data via a serial port specified by the user. This can be used to command an experiment via the serial connection.Data sent to an e-mail account can also be automatically integrated into the ground station. For this to work, a valid e-mail account and password need to be declared in the MailReceiver class. Once the (Re)Connect button is pressed, the MailReceiver connects to the specified mail server and regularly checks for updates.Files can be imported into the ground station via a FileChooser. Once Files are selected they are read and pushed to the MainController. Exporting to .csv files is currently supported by USOC. This is done via an ExportController class. All these components are described in further detail in their respective sections in this document. Figure 1 shows an overview of the internal structure of the ground station.

^^ This is displayed twice

**Comment by Pedro12909** [comment]
Here's a [pastebin link](https://pastebin.com/SfMUiNRs) to the corrected Overview page, since users can't create Pull Requests to wiki pages.

**Comment by Gyanesha** [comment]
How can I correct this , means how can I change the content of the link???

**Comment by vstarlinger** [comment]
Thanks @Pedro12909 I corrected the text and will close this issue.

**Comment by vstarlinger** [comment]
@Gyanesha The link already contains the corrected version from @Pedro12909 since he can't directly edit the wiki pages.
